### ISSUE TITLE
Typo in readme, cannot discern meaning.

### ISSUE THREAD

**Issue by tristaaan** [59naga/jaggy#11]
> Animated gif Can be convert, But, It's so very very heavy.

**Comment by 59naga** [comment]
hmm, That bug might be most fatal...
Will try to fix:

> <del>Animated gif Can be convert, But, It's so very very heavy.</del>
> 
> <br>
> 
> <ins>svg conversion of animated gif is experimental. It will take the high the CPU usage to play.</ins>

Does this sentences is wrong?

**Comment by tristaaan** [comment]
"SVG conversion of animated gif is experimental. It will take high CPU usage to play." Sounds good

Nice job on this lib btw.

**Comment by 59naga** [comment]
thx, Quality went up! :beers:
